# Step 1: Build stage
FROM node:20 AS build-stage
WORKDIR /app

# Clone and build
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/michanagatlajaswanth/cicdproject_dockerfrontend.git .
RUN npm install
RUN npm run build

# Step 2: Serve with nginx
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build-stage /app/dist ./
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
